export const data = [
  {
    id: 0,
    type: "img",
    gapY: 230,
    x: 226,
    w: 382,
    h: 476,
    src: "/ed/2.jpg",
  },
  {
    id: 1,
    type: "img",
    gapY: 328,
    x: 782,
    w: 355,
    h: 444,
    src: "/ed/3.jpg",
  },
  {
    id: 2,
    type: "img",
    gapY: 415,
    x: 1226,
    w: 405,
    h: 506,
    src: "/ed/4.jpg",
  },
  {
    id: 3,
    type: "img",
    gapY: 166,
    x: 205,
    w: 344,
    h: 429,
    src: "/ed/5.jpg",
  },
  {
    id: 4,
    type: "text",
    gapY: 578,
    headline: "Ethereal Tranquillity",
    description:
      "Inspired by the serene beauty of nature, this collection features flowing silhouettes and delicate fabrics, evoking a sense of tranquility and grace.",
  },
  {
    id: 5,
    type: "img",
    gapY: 116,
    x: 1391,
    w: 416,
    h: 518,
    src: "/ed/6.jpg",
  },
  {
    id: 6,
    type: "img",
    gapY: 490,
    x: 113,
    w: 481,
    h: 685,
    src: "/ed/7.jpg",
  },
  {
    id: 7,
    type: "img",
    gapY: 273,
    x: 792,
    w: 868,
    h: 1217,
    src: "/ed/8.jpg",
  },
  {
    id: 8,
    type: "img",
    gapY: 1115,
    x: 130,
    w: 454,
    h: 380,
    src: "/ed/9.jpg",
  },
  {
    id: 9,
    type: "text",
    gapY: 470,
    headline: "Timeless Classics",
    description:
      "Celebrating the enduring appeal of simplicity, this collection showcases timeless essentials crafted with impeccable craftsmanship and refined aesthetics.",
  },
  {
    id: 10,
    type: "img",
    gapY: 539,
    x: 1171,
    w: 524,
    h: 729,
    src: "/ed/10.jpg",
  },
  {
    id: 11,
    type: "img",
    gapY: 193,
    x: 143,
    w: 589,
    h: 737,
    src: "/ed/11.jpg",
  },
  {
    id: 12,
    type: "text",
    gapY: 1015,
    headline: "Urban Chic",
    description:
      "Infusing urban vibes with understated luxury, this collection offers sleek lines, bold accents, and versatile pieces designed for the modern cosmopolitan.",
  },
  {
    id: 13,
    type: "img",
    gapY: 130,
    x: 1416,
    w: 337,
    h: 505,
    src: "/ed/12.jpg",
  },
  {
    id: 14,
    type: "img",
    gapY: 505,
    x: 109,
    w: 970,
    h: 1215,
    src: "/ed/13.jpg",
  },
  {
    id: 15,
    type: "img",
    gapY: 1362,
    x: 990,
    w: 518,
    h: 646,
    src: "/ed/14.jpg",
  },
];
